export const CN = {
	langLabel: "EN",
	navTool: "监测平台",
	navBlog: "博客",
	navCases: "客户案例",
	ctaPrimary: "免费获取可见度诊断",
	heroBadge: "GEO · 生成式引擎优化",
	heroTitle: "见客——AI 时代，先被看见，才有生意",
	heroSub:
		"越来越多的客户不再打开搜索框，而是直接问 AI。见客帮助你的品牌在 ChatGPT、DeepSeek、豆包、Kimi、Gemini 等 AI 问答入口中被优先推荐、准确引用。",
	heroCta1: "免费获取可见度诊断",
	heroCta2: "进入监测平台",
	visionKicker: "VISION",
	visionTitle: "流量入口正在从「搜索框」迁移到「对话框」",
	pastLabel: "PAST",
	pastTitle: "人找信息",
	pastBody:
		"用户输入关键词，浏览十条蓝色链接，自己判断哪家可信。品牌竞争的是排名位置。",
	futureLabel: "NOW",
	futureTitle: "智能体找服务",
	futureBody:
		"用户提出问题，AI 直接给出一个答案和一份推荐名单。品牌竞争的是「是否进入这份名单」。",
	visionSteps: [
		{
			n: "1",
			title: "看得见",
			body: "监测品牌在主流 AI 平台上的提及率、推荐位次与引用来源。",
		},
		{
			n: "2",
			title: "改得动",
			body: "针对 AI 的内容理解方式重构官网、问答与外部信源，让模型有据可引。",
		},
		{
			n: "3",
			title: "算得清",
			body: "以可见度变化、引用增量与线索来源验证效果，而不是凭感觉投放。",
		},
	],
	insightKicker: "INSIGHT",
	insightTitle: "为什么现在必须开始做 GEO",
	insightUpdated: "数据更新：2026.09",
	insightDisclaimer:
		"以上数据引自公开来源，仅用于说明行业趋势，不构成对具体效果的承诺。第三方预测数据可能随发布方更新而变化。",
	insightCards: [
		{
			v: "-25%",
			k: "传统搜索引擎流量降幅",
			d: "Gartner 预测到 2026 年，传统搜索引擎带来的流量将下降约四分之一。",
			src: "来源：Gartner 新闻稿，2024.02",
		},
		{
			v: "-50%",
			k: "品牌自然搜索流量降幅",
			d: "Gartner 预测到 2028 年，采用 AI 助手的用户增长将使品牌自然搜索流量下降超过一半。",
			src: "来源：Gartner 新闻稿，2024.02",
		},
		{
			v: "8亿+",
			k: "ChatGPT 周活跃用户",
			d: "单一 AI 助手已具备主流媒体级别的触达规模，且仍在快速增长。",
			src: "来源：OpenAI 公开披露",
		},
		{
			v: "14",
			k: "见客覆盖 AI 平台数",
			d: "覆盖国内与海外主流 AI 搜索、问答与助手平台，持续扩展。",
			src: "来源：见客产品统计",
		},
	],
	geoKicker: "WHAT IS GEO",
	geoTitle: "GEO 解决的，是四个「AI 怎么说你」的问题",
	geoLead:
		"GEO（Generative Engine Optimization，生成式引擎优化）不是把关键词塞进网页，而是让生成式模型在回答用户问题时，能够找到你、理解你、并愿意引用你。",
	geoDims: [
		{
			tag: "BRAND",
			title: "品牌",
			q: "「XX 公司怎么样？靠谱吗？」",
			a: "AI 对你的描述是否准确、正面、信息完整，有没有把过时或错误的信息当成事实。",
		},
		{
			tag: "PRODUCT",
			title: "产品",
			q: "「有没有能解决 XX 问题的工具？」",
			a: "在具体需求场景的推荐名单里，你是否出现、排在第几、被如何概括。",
		},
		{
			tag: "RIVAL",
			title: "竞品",
			q: "「A 和 B 哪个更好？」",
			a: "对比类问题中 AI 采信了哪些信源，你的优势有没有被讲出来。",
		},
		{
			tag: "MARKET",
			title: "行业",
			q: "「XX 行业头部厂商有哪些？」",
			a: "行业级问题中你是否被列入名单，这决定了你能否进入客户的初选池。",
		},
	],
	howKicker: "HOW IT WORKS",
	howTitle: "四个引擎，构成一条可闭环的优化链路",
	engines: [
		{
			no: "01",
			title: "可见度监测引擎",
			body: "按行业构建问题库，定期在各 AI 平台采集回答，追踪提及率、推荐位次、引用来源与描述口径。",
			tags: ["问题库", "多平台采集", "趋势追踪"],
		},
		{
			no: "02",
			title: "内容优化引擎",
			body: "依据模型的内容理解偏好重构官网结构化信息、FAQ 与知识型内容，提高被检索与被引用的概率。",
			tags: ["结构化数据", "问答内容", "站内重构"],
		},
		{
			no: "03",
			title: "信源建设引擎",
			body: "梳理模型高频引用的第三方信源，围绕百科、问答社区、行业媒体与目录站建立一致的品牌事实。",
			tags: ["信源图谱", "事实一致性"],
		},
		{
			no: "04",
			title: "竞品分析引擎",
			body: "对标竞品在同一批问题下的表现，定位差距来自内容缺口、信源缺口还是口碑缺口。",
			tags: ["对标监测", "差距归因"],
		},
	],
	tierKicker: "SERVICES",
	tierTitle: "三档服务，按你的阶段选",
	tiers: [
		{
			name: "轻量版",
			who: "适合：初次了解 GEO 的中小企业",
			price: "定制方案",
			badge: "",
			items: [
				"基础可见度诊断报告",
				"20 组核心问题监测",
				"3 家竞品对标",
				"月度报告 1 次",
			],
			cta: "查看轻量版详情",
			href: "/services-lite/",
			kind: "link",
		},
		{
			name: "标准版",
			who: "适合：已有内容团队、需要持续优化的品牌",
			price: "定制方案",
			badge: "最受欢迎",
			items: [
				"全部轻量版能力",
				"100 组问题监测 + 周报",
				"站内内容优化建议与落地清单",
				"信源建设执行支持",
				"专属顾问对接",
			],
			cta: "咨询标准版方案",
			href: "#contact",
			kind: "anchor",
		},
		{
			name: "旗舰版",
			who: "适合：多品类、多市场或出海企业",
			price: "定制方案",
			badge: "",
			items: [
				"全部标准版能力",
				"多品牌 / 多市场 / 多语言监测",
				"海外平台覆盖与本地化内容",
				"竞品深度归因与季度策略复盘",
				"团队 GEO 培训",
			],
			cta: "咨询旗舰版方案",
			href: "#contact",
			kind: "anchor",
		},
	],
	platKicker: "PLATFORMS",
	platTitle: "覆盖客户真正在用的 AI 入口",
	platGroups: [
		{
			label: "国内平台",
			items: [
				"DeepSeek",
				"豆包",
				"Kimi",
				"通义千问",
				"文心一言",
				"腾讯元宝",
				"智谱清言",
				"秘塔搜索",
			],
		},
		{
			label: "海外平台",
			items: ["ChatGPT", "Gemini", "Claude", "Perplexity", "Copilot", "Grok"],
		},
	],
	whyKicker: "WHY JIANKE",
	whyTitle: "和通用 SEO 工具、纯监测工具的区别",
	whyColDim: "对比维度",
	whyColUs: "见客 GEO",
	whyColSeo: "通用 SEO 工具",
	whyColMon: "纯监测工具",
	compareRows: [
		{
			dim: "优化对象",
			us: "生成式模型的回答与引用",
			seo: "搜索引擎排名页面",
			mon: "不做优化",
		},
		{
			dim: "平台覆盖",
			us: "国内 + 海外 14 个 AI 平台",
			seo: "百度 / Google 为主",
			mon: "通常 2–4 个平台",
		},
		{
			dim: "交付内容",
			us: "监测 + 内容优化 + 信源建设",
			seo: "关键词与外链建议",
			mon: "数据看板与报告",
		},
		{
			dim: "效果验证",
			us: "可见度变化与引用增量可回溯",
			seo: "以排名与流量为主",
			mon: "只呈现现状",
		},
		{
			dim: "落地方式",
			us: "顾问陪跑，给到可执行清单",
			seo: "工具自助",
			mon: "工具自助",
		},
	],
	cliKicker: "CLIENTS",
	cliTitle: "他们已经在 AI 答案里被看见",
	cliMore: "查看全部案例",
	cliDisclaimer:
		"示例：以上客户名称与证言为占位内容，正式上线前将替换为经客户授权的真实信息。",
	clientLogos: [
		"制造 · A 集团",
		"美妆 · B 品牌",
		"SaaS · C 科技",
		"教育 · D 学院",
		"医疗 · E 健康",
		"出海 · F 电商",
	],
	testimonials: [
		{
			tag: "示例 · 工业制造",
			quote:
				"以前客户问 AI「有哪些国产供应商」，名单里没有我们。做了三个月，主流平台的提及率从零到稳定进入前五。",
			who: "市场负责人 · A 集团",
		},
		{
			tag: "示例 · SaaS",
			quote:
				"最有价值的不是报告，而是那份内容整改清单，我们内容团队照着做就行。",
			who: "增长负责人 · C 科技",
		},
		{
			tag: "示例 · 跨境电商",
			quote:
				"海外平台的表现我们原本完全看不见，现在每周能看到变化，投放也知道该补哪块内容。",
			who: "品牌总监 · F 电商",
		},
	],
	aboutKicker: "ABOUT",
	aboutTitle: "我们只做一件事：让品牌在 AI 答案里出现",
	aboutP1:
		"见客由一支来自搜索、内容营销与 AI 工程背景的团队创立。我们相信，AI 问答正在成为新的第一触点，而绝大多数企业还没有为此做过任何准备。",
	aboutP2:
		"我们把 AI 可见度做成可以被监测、被优化、被验证的工作流，而不是一次性的投放服务。",
	aboutStats: [
		{ v: "14", k: "覆盖 AI 平台" },
		{ v: "50+", k: "服务客户" },
		{ v: "20万+", k: "累计监测问答" },
		{ v: "7×24", k: "监测频率" },
	],
	ctaTitle: "先看看客户问 AI 时，AI 怎么说你",
	ctaBody:
		"留下联系方式，我们会基于你所在行业的真实问题，出具一份免费的 AI 可见度诊断。",
	footTag: "GEO 服务与监测平台，让品牌在 AI 答案中被看见。",
	footContact: "联系我们",
	footPhone: "电话：400-000-0000",
	footMail: "邮箱：hello@jianke.com",
	footAddr: "地址：待补充",
	footCopy: "© 2026 见客 JianKe. All rights reserved.",
	footIcp: "京ICP备00000000号",
	footColTitles: ["产品与服务", "了解见客", "资源"],
	formTitle: "免费 AI 可见度诊断",
	formSub: "填写后 1 个工作日内，顾问会联系你确认行业与问题范围。",
	formNeed: "需求描述",
	formNeedPh: "简单说说你希望在哪些 AI 平台被看见（选填）",
	formSubmit: "提交申请",
	formPrivacy: "我们仅将信息用于本次咨询，不会对外提供。",
	formDoneTitle: "已收到，谢谢！",
	formDoneBody: "我们会在 1 个工作日内与你联系。急需沟通可拨打 400-000-0000。",
	formClose: "关闭",
	formFields: [
		{
			name: "name",
			label: "姓名 *",
			ph: "如：张先生",
			required: true,
			span: "auto",
		},
		{
			name: "phone",
			label: "手机 *",
			ph: "11 位手机号",
			required: true,
			span: "auto",
		},
		{
			name: "company",
			label: "公司名称 *",
			ph: "公司全称",
			required: true,
			span: "auto",
		},
		{
			name: "role",
			label: "职位",
			ph: "如：市场负责人",
			required: false,
			span: "auto",
		},
		{
			name: "industry",
			label: "所属行业",
			ph: "如：工业制造",
			required: false,
			span: "1/-1",
		},
	],
	nav: [
		{ href: "#vision", label: "愿景", id: "vision" },
		{ href: "#insight", label: "行业洞察", id: "insight" },
		{ href: "#what-is-geo", label: "什么是GEO", id: "what-is-geo" },
		{ href: "#how-it-works", label: "产品能力", id: "how-it-works" },
		{ href: "#service-tiers", label: "服务方案", id: "service-tiers" },
		{ href: "#why-us", label: "为什么选见客", id: "why-us" },
		{ href: "#clients", label: "客户案例", id: "clients" },
		{ href: "#about", label: "关于我们", id: "about" },
	],
	heroStats: [
		{ v: "14", k: "覆盖 AI 平台" },
		{ v: "7×24", k: "持续监测" },
		{ v: "1 个工作日", k: "诊断响应" },
	],
};

export const EN = {
	langLabel: "中文",
	navTool: "Monitor",
	navBlog: "Blog",
	navCases: "Case Studies",
	ctaPrimary: "Get a free visibility audit",
	heroBadge: "GEO · Generative Engine Optimization",
	heroTitle: "JianKe — in the AI era, being seen comes before being chosen",
	heroSub:
		"Buyers no longer open a search box; they ask an AI. JianKe helps your brand get recommended and accurately cited across ChatGPT, DeepSeek, Doubao, Kimi, Gemini and more.",
	heroCta1: "Get a free visibility audit",
	heroCta2: "Open the monitor",
	visionKicker: "VISION",
	visionTitle: "The entry point is moving from the search box to the chat box",
	pastLabel: "PAST",
	pastTitle: "People find information",
	pastBody:
		"Users typed keywords, scanned ten blue links and judged for themselves. Brands competed for rank.",
	futureLabel: "NOW",
	futureTitle: "Agents find services",
	futureBody:
		"Users ask a question and the AI returns one answer with a shortlist. Brands compete to be on that shortlist.",
	visionSteps: [
		{
			n: "1",
			title: "See it",
			body: "Measure mention rate, recommendation position and cited sources across major AI platforms.",
		},
		{
			n: "2",
			title: "Fix it",
			body: "Rebuild site content, FAQs and external sources the way models actually read them.",
		},
		{
			n: "3",
			title: "Prove it",
			body: "Validate with visibility deltas, citation growth and lead attribution instead of gut feel.",
		},
	],
	insightKicker: "INSIGHT",
	insightTitle: "Why GEO cannot wait",
	insightUpdated: "Updated 2026.09",
	insightDisclaimer:
		"Figures come from public sources and illustrate market direction only; they are not a promise of results. Third-party forecasts may be revised by their publishers.",
	insightCards: [
		{
			v: "-25%",
			k: "Drop in traditional search volume",
			d: "Gartner forecasts search engine volume will fall about a quarter by 2026.",
			src: "Source: Gartner press release, 2024.02",
		},
		{
			v: "-50%",
			k: "Drop in brand organic traffic",
			d: "Gartner forecasts brands' organic search traffic will fall over 50% by 2028 as consumers adopt AI assistants.",
			src: "Source: Gartner press release, 2024.02",
		},
		{
			v: "800M+",
			k: "ChatGPT weekly users",
			d: "A single assistant now has mass-media reach, and it is still growing fast.",
			src: "Source: OpenAI public disclosure",
		},
		{
			v: "14",
			k: "AI platforms covered",
			d: "Major Chinese and global AI search, Q&A and assistant platforms, continuously expanded.",
			src: "Source: JianKe product data",
		},
	],
	geoKicker: "WHAT IS GEO",
	geoTitle: "Four questions about how AI talks about you",
	geoLead:
		"GEO is not stuffing keywords into pages. It is making sure generative models can find you, understand you, and are willing to cite you when answering a buyer's question.",
	geoDims: [
		{
			tag: "BRAND",
			title: "Brand",
			q: "\u201cIs this company any good?\u201d",
			a: "Whether the AI's description of you is accurate, complete and current.",
		},
		{
			tag: "PRODUCT",
			title: "Product",
			q: "\u201cWhat tool solves this problem?\u201d",
			a: "Whether you appear on the shortlist, in what position, and how you are summarised.",
		},
		{
			tag: "RIVAL",
			title: "Competitors",
			q: "\u201cA or B — which is better?\u201d",
			a: "Which sources the AI trusts in comparisons, and whether your advantages come through.",
		},
		{
			tag: "MARKET",
			title: "Category",
			q: "\u201cWho leads this industry?\u201d",
			a: "Whether you make the category list at all — which decides if you reach the buyer's shortlist.",
		},
	],
	howKicker: "HOW IT WORKS",
	howTitle: "Four engines, one closed optimization loop",
	engines: [
		{
			no: "01",
			title: "Visibility monitoring",
			body: "Build an industry prompt set, sample answers across platforms on a schedule, and track mentions, position, sources and wording.",
			tags: ["Prompt sets", "Multi-platform", "Trends"],
		},
		{
			no: "02",
			title: "Content optimization",
			body: "Restructure site data, FAQs and knowledge content around how models read, raising the odds of retrieval and citation.",
			tags: ["Structured data", "Q&A content", "Site rebuild"],
		},
		{
			no: "03",
			title: "Source building",
			body: "Map the third-party sources models cite most and align brand facts across encyclopaedias, Q&A communities, trade media and directories.",
			tags: ["Source map", "Fact consistency"],
		},
		{
			no: "04",
			title: "Competitive analysis",
			body: "Benchmark rivals on the same prompts and attribute the gap to content, sources or reputation.",
			tags: ["Benchmarking", "Gap attribution"],
		},
	],
	tierKicker: "SERVICES",
	tierTitle: "Three tiers, matched to your stage",
	tiers: [
		{
			name: "Lite",
			who: "For SMBs exploring GEO for the first time",
			price: "Custom quote",
			badge: "",
			items: [
				"Baseline visibility audit",
				"20 core prompts monitored",
				"3 competitors benchmarked",
				"One monthly report",
			],
			cta: "See Lite details",
			href: "/services-lite/",
			kind: "link",
		},
		{
			name: "Standard",
			who: "For brands with a content team running continuous optimization",
			price: "Custom quote",
			badge: "Most popular",
			items: [
				"Everything in Lite",
				"100 prompts monitored + weekly report",
				"On-site content fixes with an action list",
				"Source-building execution support",
				"Dedicated consultant",
			],
			cta: "Talk about Standard",
			href: "#contact",
			kind: "anchor",
		},
		{
			name: "Flagship",
			who: "For multi-category, multi-market or global brands",
			price: "Custom quote",
			badge: "",
			items: [
				"Everything in Standard",
				"Multi-brand / market / language monitoring",
				"Global platform coverage and localisation",
				"Deep competitive attribution, quarterly review",
				"GEO training for your team",
			],
			cta: "Talk about Flagship",
			href: "#contact",
			kind: "anchor",
		},
	],
	platKicker: "PLATFORMS",
	platTitle: "Coverage of the AI entry points buyers actually use",
	platGroups: [
		{
			label: "China",
			items: [
				"DeepSeek",
				"Doubao",
				"Kimi",
				"Qwen",
				"ERNIE Bot",
				"Tencent Yuanbao",
				"Zhipu Qingyan",
				"Metaso",
			],
		},
		{
			label: "Global",
			items: ["ChatGPT", "Gemini", "Claude", "Perplexity", "Copilot", "Grok"],
		},
	],
	whyKicker: "WHY JIANKE",
	whyTitle: "How we differ from SEO suites and monitoring-only tools",
	whyColDim: "Dimension",
	whyColUs: "JianKe GEO",
	whyColSeo: "SEO suites",
	whyColMon: "Monitoring tools",
	compareRows: [
		{
			dim: "What is optimized",
			us: "Model answers and citations",
			seo: "Search result rankings",
			mon: "Nothing is optimized",
		},
		{
			dim: "Platform coverage",
			us: "14 platforms, China + global",
			seo: "Mainly Baidu / Google",
			mon: "Usually 2–4 platforms",
		},
		{
			dim: "Deliverables",
			us: "Monitoring + content + sources",
			seo: "Keyword and backlink advice",
			mon: "Dashboards and reports",
		},
		{
			dim: "Proof of results",
			us: "Traceable visibility and citation deltas",
			seo: "Rank and traffic",
			mon: "Current state only",
		},
		{
			dim: "Delivery model",
			us: "Consultant-led, executable action lists",
			seo: "Self-serve tool",
			mon: "Self-serve tool",
		},
	],
	cliKicker: "CLIENTS",
	cliTitle: "Already showing up in AI answers",
	cliMore: "All case studies",
	cliDisclaimer:
		"Sample: client names and quotes are placeholders and will be replaced with approved, real references before launch.",
	clientLogos: [
		"Mfg · Group A",
		"Beauty · Brand B",
		"SaaS · C Tech",
		"Edu · D Academy",
		"Health · E Care",
		"Cross-border · F",
	],
	testimonials: [
		{
			tag: "Sample · Manufacturing",
			quote:
				"When buyers asked AI for domestic suppliers, we weren't on the list. Three months in, we're consistently in the top five on the major platforms.",
			who: "Head of Marketing · Group A",
		},
		{
			tag: "Sample · SaaS",
			quote:
				"The valuable part wasn't the report, it was the content fix list our team could just work through.",
			who: "Head of Growth · C Tech",
		},
		{
			tag: "Sample · Cross-border",
			quote:
				"We had zero view of overseas platforms. Now we see weekly movement and know which content to fill.",
			who: "Brand Director · F",
		},
	],
	aboutKicker: "ABOUT",
	aboutTitle: "We do one thing: get brands into AI answers",
	aboutP1:
		"JianKe was founded by a team from search, content marketing and AI engineering. We believe AI answers are becoming the first touchpoint, and most companies have done nothing to prepare for it.",
	aboutP2:
		"We turn AI visibility into a workflow that can be measured, optimized and verified — not a one-off campaign.",
	aboutStats: [
		{ v: "14", k: "AI platforms" },
		{ v: "50+", k: "Clients served" },
		{ v: "200k+", k: "Answers sampled" },
		{ v: "7×24", k: "Monitoring" },
	],
	ctaTitle: "See what AI says about you when buyers ask",
	ctaBody:
		"Leave your details and we'll run a free AI visibility audit on the real questions asked in your industry.",
	footTag: "GEO services and monitoring, so your brand is seen in AI answers.",
	footContact: "Contact",
	footPhone: "Tel: 400-000-0000",
	footMail: "Email: hello@jianke.com",
	footAddr: "Address: TBC",
	footCopy: "© 2026 JianKe. All rights reserved.",
	footIcp: "ICP No. 00000000",
	footColTitles: ["Products & services", "Company", "Resources"],
	formTitle: "Free AI visibility audit",
	formSub:
		"A consultant will contact you within one business day to confirm scope.",
	formNeed: "What do you need?",
	formNeedPh: "Which AI platforms matter most to you? (optional)",
	formSubmit: "Submit",
	formPrivacy: "Used for this enquiry only, never shared.",
	formDoneTitle: "Received — thank you!",
	formDoneBody:
		"We'll be in touch within one business day. Urgent? Call 400-000-0000.",
	formClose: "Close",
	formFields: [
		{
			name: "name",
			label: "Name *",
			ph: "Your name",
			required: true,
			span: "auto",
		},
		{
			name: "phone",
			label: "Phone *",
			ph: "Mobile number",
			required: true,
			span: "auto",
		},
		{
			name: "company",
			label: "Company *",
			ph: "Legal name",
			required: true,
			span: "auto",
		},
		{
			name: "role",
			label: "Role",
			ph: "e.g. Head of Marketing",
			required: false,
			span: "auto",
		},
		{
			name: "industry",
			label: "Industry",
			ph: "e.g. Manufacturing",
			required: false,
			span: "1/-1",
		},
	],
	nav: [
		{ href: "#vision", label: "Vision", id: "vision" },
		{ href: "#insight", label: "Insight", id: "insight" },
		{ href: "#what-is-geo", label: "What is GEO", id: "what-is-geo" },
		{ href: "#how-it-works", label: "Capabilities", id: "how-it-works" },
		{ href: "#service-tiers", label: "Services", id: "service-tiers" },
		{ href: "#why-us", label: "Why us", id: "why-us" },
		{ href: "#clients", label: "Clients", id: "clients" },
		{ href: "#about", label: "About", id: "about" },
	],
	heroStats: [
		{ v: "14", k: "AI platforms" },
		{ v: "7×24", k: "Monitoring" },
		{ v: "1 day", k: "Audit response" },
	],
};
